name: CD (Deploy to GitHub Pages)
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: |
          yarn
          yarn run build

      - name: Deploy Build to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist

      - name: Generate docs
        run: yarn run docs

      - name: Deploy docs to jsdoc branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: jsdoc
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
