# CI pipeline
# Ensure code is free of building, linting, and testing errors
name: CI

# run on all pushes or PR with main
on:
  push:
  pull_request:
    branches: [ main ]
    
# set `run` options
defaults:
  run:
    shell: bash

# build, lint and test
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2     
      
      - name: Install node
        uses: actions/setup-node@v2  
        
      - name: Build project
        run: |
          yarn
          yarn run build
      
      - name: Run linting checks
        run: |
          yarn
          yarn run lint
      
      - name: Run tests
        run: |
          yarn
          yarn run test
